In [61]:
#downloading file
link = "https://library.startlearninglabs.uw.edu/DATASCI420/2019/Datasets/Intrusion%20Detection.csv"
filename = link

In [62]:
#importing necessary libraries
import numpy as np
import sklearn
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score


In [63]:
# Importing data set in to dataframe
import pandas as pd
#saving the file into pandas dataframe
df = pd.read_csv(filename)

In [64]:
df

duration protocol_type service  flag  src_bytes  dst_bytes  land  \
0             0           tcp    http    SF        181       5450     0   
1             0           tcp    http    SF        239        486     0   
2             0           tcp    http    SF        235       1337     0   
3             0           tcp    http    SF        219       1337     0   
4             0           tcp    http    SF        217       2032     0   
...         ...           ...     ...   ...        ...        ...   ...   
97303       321           tcp  telnet  RSTO       1506       1887     0   
97304        45           tcp  telnet    SF       2336       4201     0   
97305       176           tcp  telnet    SF       1559       2732     0   
97306        61           tcp  telnet    SF       2336       4194     0   
97307        47           tcp  telnet    SF       2402       3816     0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                   0       0    0  ...                   9   
1                   0       0    0  ...                  19   
2                   0       0    0  ...                  29   
3                   0       0    0  ...                  39   
4                   0       0    0  ...                  49   
...               ...     ...  ...  ...                 ...   
97303               0       0    0  ...                   6   
97304               0       0    3  ...                   7   
97305               0       0    3  ...                   8   
97306               0       0    3  ...                   9   
97307               0       0    3  ...                  10   

       dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                         1.0                     0.0   
1                         1.0                     0.0   
2                         1.0                     0.0   
3                         1.0                     0.0   
4                         1.0                     0.0   
...                       ...                     ...   
97303                     1.0                     0.0   
97304                     1.0                     0.0   
97305                     1.0                     0.0   
97306                     1.0                     0.0   
97307                     1.0                     0.0   

       dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                             0.11                          0.0   
1                             0.05                          0.0   
2                             0.03                          0.0   
3                             0.03                          0.0   
4                             0.02                          0.0   
...                            ...                          ...   
97303                         0.17                          0.0   
97304                         0.14                          0.0   
97305                         0.12                          0.0   
97306                         0.11                          0.0   
97307                         0.10                          0.0   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.0                       0.0                  0.00   
1                       0.0                       0.0                  0.00   
2                       0.0                       0.0                  0.00   
3                       0.0                       0.0                  0.00   
4                       0.0                       0.0                  0.00   
...                     ...                       ...                   ...   
97303                   0.0                       0.0                  0.17   
97304                   0.0                       0.0                  0.14   
97305                   0.0                       0.0                  0.12   
97306                   0.0                       0.0                

In [65]:
df.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate          

In [66]:
#dropping colums
del df['protocol_type']

In [67]:
del df['service']
del df['flag']

In [68]:
#feature selection
features = df.iloc[:, 0:38].values

In [69]:
#target label
label = df.iloc[:, 38].values

In [70]:
x_train, x_test, y_train, y_test = train_test_split(features, label, test_size = .33, random_state = 42)

In [71]:
x_test

array([[   0.,  224.,  515., ...,    0.,    0.,    0.],
       [   0.,   42.,   42., ...,    0.,    0.,    0.],
       [   0., 1010.,    0., ...,    0.,    0.,    0.],
       ...,
       [   0.,   30.,    0., ...,    0.,    0.,    0.],
       [   0.,  313., 2159., ...,    0.,    0.,    0.],
       [   0.,  241., 4137., ...,    0.,    0.,    0.]])

In [72]:
#bernoulli model
bernNB = BernoulliNB()
bernNB.fit(x_train, y_train)
print (bernNB)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)


In [73]:
y_expected = y_test
y_predicted = bernNB.predict(x_test)

In [74]:
#acccuracy of the model
from sklearn.metrics import accuracy_score
accuracy_score(y_expected, y_predicted)

0.9995951669157948

In [75]:
#confusion metrics 
confusion_matrix(y_expected, y_predicted)

array([[32090,    10],
       [    3,     9]], dtype=int64)

In [76]:
#Multinom
multiNB = MultinomialNB()
multiNB.fit(x_train, y_train)
print (multiNB)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [77]:
y_expected = y_test
y_predicted = multiNB.predict(x_test)

In [78]:
accuracy_score(y_expected, y_predicted)

0.8693946188340808

In [79]:
confusion_matrix(y_expected, y_predicted)

array([[27913,  4187],
       [    7,     5]], dtype=int64)

In [80]:
#Gaus
gausNB = GaussianNB()
gausNB.fit(x_train, y_train)
print (gausNB)

GaussianNB(priors=None, var_smoothing=1e-09)


In [81]:
y_expected = y_test
y_predicted = gausNB.predict(x_test)

In [82]:
accuracy_score(y_expected, y_predicted)

0.9851145989038366

In [83]:
confusion_matrix(y_expected, y_predicted)

array([[31623,   477],
       [    1,    11]], dtype=int64)

In [84]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE

In [85]:
#applying SMOTE to handle class imbalance 

In [86]:
#current class imbalance 
print('Resampled dataset shape {}'.format(Counter(label)))

Resampled dataset shape Counter({0: 97278, 1: 30})


In [87]:
#new class balance
sm = SMOTE(random_state=42)
nfeatures, nlabel = sm.fit_sample(features, label)
print('Resampled dataset shape {}'.format(Counter(nlabel)))

Resampled dataset shape Counter({0: 97278, 1: 97278})


In [88]:
#reapplying models
x_train, x_test, y_train, y_test = train_test_split(nfeatures, nlabel, test_size = .33, random_state = 42)

In [89]:
#bernoulli
bernNB = BernoulliNB()
bernNB.fit(x_train, y_train)
print (bernNB)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)


In [90]:
y_expected = y_test
y_predicted = bernNB.predict(x_test)

In [91]:
accuracy_score(y_expected, y_predicted)

0.8988380786243848

In [92]:
confusion_matrix(y_expected, y_predicted)

array([[31928,    27],
       [ 6468, 25781]], dtype=int64)

In [93]:
#Multinom
multiNB = MultinomialNB()
multiNB.fit(x_train, y_train)
print (multiNB)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [94]:
y_expected = y_test
y_predicted = multiNB.predict(x_test)

In [95]:
accuracy_score(y_expected, y_predicted)

0.9401750669740203

In [96]:
confusion_matrix(y_expected, y_predicted)

array([[29234,  2721],
       [ 1120, 31129]], dtype=int64)

In [97]:
#Gaus
gausNB = GaussianNB()
gausNB.fit(x_train, y_train)
print (gausNB)

GaussianNB(priors=None, var_smoothing=1e-09)


In [98]:
y_expected = y_test
y_predicted = gausNB.predict(x_test)

In [99]:
accuracy_score(y_expected, y_predicted)

0.9862158120989346

In [100]:
confusion_matrix(y_expected, y_predicted)

array([[31371,   584],
       [  301, 31948]], dtype=int64)

In [101]:
#it appears that with class imbalance althrough the accuracy was high but the balance btw TN and FN, FP and TP 
#was highly imbalance hence wasn't truly predicting spam. with the class imbance removed, that 
#distribution is balanced. and bernulli bayes is predicting with 89% accuracy